export const users = [
    {
        id: 1,
        name: "John Doe",
        currentRole: "IT Manager",
        company: "Codex IT",
        previousRole: "Frontend Developer",
        previousCompany: "Mathosagar IT Solution",
        rating: 4.5,
        reviews: 10,
        attributes: ["98% Would work again", "Known for Leadership"],
    },
    {
        id: 2,
        name: "Jane smith",
        company: "Microsoft",
        currentRole: "IT Manager",
        previousRole: "Frontend Developer",
        previousCompany: "Mathosagar IT Solution",
        rating: 4.5,
        reviews: 10,
        attributes: ["98% Would work again", "Known for Leadership"],
    },
    {
        id: 3,
        name: "Alice Johnson",
        company: "Amazon",
        currentRole: "IT Manager",
        previousRole: "Frontend Developer",
        previousCompany: "Mathosagar IT Solution",
        rating: 4.5,
        reviews: 10,
        attributes: ["98% Would work again", "Known for Leadership"],
    },
    {
        id: 4,
        name: "Rasel Kibria",
        company: "Impress Newtex",
        currentRole: "IT Manager",
        previousRole: "Frontend Developer",
        previousCompany: "Mathosagar IT Solution",
        rating: 4.5,
        reviews: 10,
        attributes: ["98% Would work again", "Known for Leadership"],
    }
]