export const users = [
  {
    id: 1,
    name: "John Doe",
    image:"https://i.pravatar.cc/150?img=1" ,
    currentRole: "IT Manager",
    company: "Codex IT",
    previousRole: "Frontend Developer",
    previousCompany: "Mathosagar IT Solution",
    rating: 4.5,
    reviews: 10,
    attributes: ["98% Would work again", "Known for Leadership"],
  },
  {
    id: 2,
    name: "Jane smith",
    image:"https://i.pravatar.cc/150?img=2" ,
    company: "Microsoft",
    currentRole: "IT Manager",
    previousRole: "Frontend Developer",
    previousCompany: "Mathosagar IT Solution",
    rating: 4.5,
    reviews: 10,
    attributes: ["98% Would work again", "Known for Leadership"],
  },
  {
    id: 3,
    name: "Alice Johnson",
    image:"https://i.pravatar.cc/150?img=3" ,
    company: "Amazon",
    currentRole: "IT Manager",
    previousRole: "Frontend Developer",
    previousCompany: "Mathosagar IT Solution",
    rating: 4.5,
    reviews: 10,
    attributes: ["98% Would work again", "Known for Leadership"],
  },
  {
    id: 4,
    name: "Rasel Kibria",
    image:"https://i.pravatar.cc/150?img=4" ,
    company: "Impress Newtex",
    currentRole: "IT Manager",
    previousRole: "Frontend Developer",
    previousCompany: "Mathosagar IT Solution",
    rating: 4.5,
    reviews: 10,
    attributes: ["98% Would work again", "Known for Leadership"],
  },
  {
    id: 5,
    name: "Adnan Hossain Muhid",
    image:"https://i.pravatar.cc/150?img=5" ,
    company: "Impress Newtex",
    currentRole: "IT Manager",
    previousRole: "Frontend Developer",
    previousCompany: "Mathosagar IT Solution",
    rating: 4.5,
    reviews: 10,
    attributes: ["98% Would work again", "Known for Leadership"],
  },
  {
    id: 6,
    name: "Md Jamal Uddin",
    image:"https://i.pravatar.cc/150?img=6" ,
    company: "Scandex pvt ltd",
    currentRole: "IT Manager",
    previousRole: "Frontend Developer",
    previousCompany: "Mathosagar IT Solution",
    rating: 4.5,
    reviews: 10,
    attributes: ["98% Would work again", "Known for Leadership"],
  },
  {
    id: 7,
    name: "John Doe",
    image:"https://i.pravatar.cc/150?img=7" ,
    currentRole: "IT Manager",
    company: "Codex IT",
    previousRole: "Frontend Developer",
    previousCompany: "Mathosagar IT Solution",
    rating: 4.5,
    reviews: 10,
    attributes: ["98% Would work again", "Known for Leadership"],
  },
  {
    id: 8,
    name: "Sarah Ahmed",
    image:"https://i.pravatar.cc/150?img=8" ,
    currentRole: "UI/UX Designer",
    company: "PixelCraft Studio",
    previousRole: "Graphic Designer",
    previousCompany: "DesignMate",
    rating: 4.7,
    reviews: 12,
    attributes: ["95% Creative Thinker", "Strong Communication"],
  },
  {
    id: 9,
    name: "Michael Lee",
    image:"https://i.pravatar.cc/150?img=9" ,
    currentRole: "Full Stack Developer",
    company: "TechNova",
    previousRole: "Backend Developer",
    previousCompany: "SoftXpert",
    rating: 4.8,
    reviews: 18,
    attributes: ["99% Reliable", "Fast Problem Solver"],
  },
  {
    id: 10,
    name: "Emily Carter",
    image:"https://i.pravatar.cc/150?img=10" ,
    currentRole: "Project Manager",
    company: "NextGen Systems",
    previousRole: "Assistant PM",
    previousCompany: "Planify Tech",
    rating: 4.4,
    reviews: 9,
    attributes: ["96% Organized", "Good Leadership Skills"],
  },
  {
    id: 11,
    name: "David Johnson",
    image:"https://i.pravatar.cc/150?img=11" ,
    currentRole: "Software Engineer",
    company: "CodeBase Ltd.",
    previousRole: "Intern Developer",
    previousCompany: "InnovateX",
    rating: 4.6,
    reviews: 11,
    attributes: ["97% Problem Solver", "Team Player"],
  },
  {
    id: 12,
    name: "Ayesha Khan",
    image:"https://i.pravatar.cc/150?img=12" ,
    currentRole: "Frontend Developer",
    company: "WebVerse",
    previousRole: "UI Developer",
    previousCompany: "SkySoft",
    rating: 4.9,
    reviews: 22,
    attributes: ["100% Reliable", "Pixel Perfect Designs"],
  },
  {
    id: 13,
    name: "Liam Smith",
    image:"https://i.pravatar.cc/150?img=13" ,
    currentRole: "Data Analyst",
    company: "InsightPro",
    previousRole: "Research Assistant",
    previousCompany: "DataSphere",
    rating: 4.3,
    reviews: 7,
    attributes: ["92% Analytical", "Strong Excel Skills"],
  },
  {
    id: 14,
    name: "Sophia Brown",
    image:"https://i.pravatar.cc/150?img=14" ,
    currentRole: "Marketing Specialist",
    company: "Brandify Media",
    previousRole: "Content Writer",
    previousCompany: "StoryLab",
    rating: 4.6,
    reviews: 13,
    attributes: ["97% Creative Ideas", "Strong Presentation Skills"],
  },
  {
    id: 15,
    name: "Noah Wilson",
    image:"https://i.pravatar.cc/150?img=15" ,
    currentRole: "DevOps Engineer",
    company: "CloudSphere",
    previousRole: "System Administrator",
    previousCompany: "HostNet",
    rating: 4.7,
    reviews: 15,
    attributes: ["95% Reliable", "Strong Automation Skills"],
  },
  {
    id: 16,
    name: "Olivia Martin",
    image:"https://i.pravatar.cc/150?img=16" ,
    currentRole: "QA Engineer",
    company: "TestHub",
    previousRole: "Manual Tester",
    previousCompany: "AppCheck",
    rating: 4.5,
    reviews: 8,
    attributes: ["98% Detail-Oriented", "Consistent Performer"],
  },
  {
    id: 17,
    name: "Ethan Walker",
    image:"https://i.pravatar.cc/150?img=17" ,
    currentRole: "Product Manager",
    company: "Innovento",
    previousRole: "Business Analyst",
    previousCompany: "Strategix",
    rating: 4.8,
    reviews: 14,
    attributes: ["99% Strategic Thinking", "Effective Leader"],
  },
  {
    id: 18,
    name: "Isabella Garcia",
    image:"https://i.pravatar.cc/150?img=18" ,
    currentRole: "HR Executive",
    company: "PeopleFirst",
    previousRole: "Recruiter",
    previousCompany: "TalentCraft",
    rating: 4.4,
    reviews: 10,
    attributes: ["94% Empathetic", "Great Team Support"],
  },
  {
    id: 19,
    name: "William Scott",
    image:"https://i.pravatar.cc/150?img=19" ,
    currentRole: "Backend Developer",
    company: "CodeStream",
    previousRole: "Junior Developer",
    previousCompany: "AppSphere",
    rating: 4.6,
    reviews: 17,
    attributes: ["97% Clean Code", "Strong API Design"],
  },
  {
    id: 20,
    name: "Mia Robinson",
    image:"https://i.pravatar.cc/150?img=20" ,
    currentRole: "SEO Expert",
    company: "RankBoost",
    previousRole: "Digital Marketer",
    previousCompany: "WebGrow",
    rating: 4.5,
    reviews: 9,
    attributes: ["95% Keyword Optimization", "Strong Analytics Skills"],
  },
  {
    id: 21,
    name: "James Anderson",
    image:"https://i.pravatar.cc/150?img=21" ,
    currentRole: "Cybersecurity Analyst",
    company: "SecureNet",
    previousRole: "Network Engineer",
    previousCompany: "TechGuard",
    rating: 4.9,
    reviews: 16,
    attributes: ["99% Threat Detection", "Trusted by Team"],
  },
];
